In [682]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Average Wind Speed Data of Nepal from different Districts (2005 - 2016)
<br>
<li>Last Modified: July 6, 2019
<li>Data Format: CSV

In [683]:
dataset = pd.read_csv('average-wind-speed-by-station-km_hr.csv')

In [684]:
df = pd.DataFrame(dataset)
real = df

In [685]:
df = df.T

In [686]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
Station Name,Arghakhanchi (Khanchikot),Bardia (Chishapani),"Rupandehi,Bhairahawa Agriculture","Bhojpur,Bhojpur*","Dadeldhura,Dadeldhura","Dhankuta,Pakhribas","Dhankuta, Dhankuta",Dolakha (Jiri),"Doti, Dipayal","Ilam , Ilam Tea State",...,"Banke,Khajura","Banke, Sikta","Okhaldhunga,Okhaldhunga","Parsa, Parwanipur","Kaski, Pokhara Airport","Siraha, Lahan","Sunsari ,Tarahara","Surkhet ,Birendranagar","Surkhet ,Pusmacamp","Taplejung, Taplejung"
2005,6.6,7.2,2.7,-,3.4,1.2,3.9,3.2,1.4,1.2,...,2.2,1.9,2.7,2.5,2.3,3.9,4.5,1.6,1.6,2.5
2006,NaN,NaN,2.7,-,2.9,1.3,3.5,3.1,2,1.2,...,1.9,1.5,4.3,1.7,NaN,NaN,7,1.2,1.9,NaN
2007,NaN,NaN,NaN,-,2.6,N.A,3.2,N.A,1.9,NaN,...,1.9,0.6,4.3,0.7,1.9,N.A,6.4,1.3,1.6,1.5
2008,NaN,NaN,NaN,-,2.6,0.9,3.3,3,1.5,NaN,...,1.9,0.8,3.8,1.3,2.1,1.9,6.2,1.6,N.A,1.8

In [687]:
df.columns

RangeIndex(start=0, stop=32, step=1)

In [688]:
df = df.rename(index={'Station Name':'Year'})

In [689]:
df.head(13)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
Year,Arghakhanchi (Khanchikot),Bardia (Chishapani),"Rupandehi,Bhairahawa Agriculture","Bhojpur,Bhojpur*","Dadeldhura,Dadeldhura","Dhankuta,Pakhribas","Dhankuta, Dhankuta",Dolakha (Jiri),"Doti, Dipayal","Ilam , Ilam Tea State",...,"Banke,Khajura","Banke, Sikta","Okhaldhunga,Okhaldhunga","Parsa, Parwanipur","Kaski, Pokhara Airport","Siraha, Lahan","Sunsari ,Tarahara","Surkhet ,Birendranagar","Surkhet ,Pusmacamp","Taplejung, Taplejung"
2005,6.6,7.2,2.7,-,3.4,1.2,3.9,3.2,1.4,1.2,...,2.2,1.9,2.7,2.5,2.3,3.9,4.5,1.6,1.6,2.5
2006,NaN,NaN,2.7,-,2.9,1.3,3.5,3.1,2,1.2,...,1.9,1.5,4.3,1.7,NaN,NaN,7,1.2,1.9,NaN
2007,NaN,NaN,NaN,-,2.6,N.A,3.2,N.A,1.9,NaN,...,1.9,0.6,4.3,0.7,1.9,N.A,6.4,1.3,1.6,1.5
2008,NaN,NaN,NaN,-,2.6,0.9,3.3,3,1.5,NaN,...,1.9,0.8,3.8,1.3,2.1,1.9,6.2,1.6,N.A,1.8
2009,NaN,NaN,NaN,-,2.8,N.A,3.1,N.A,1.6,NaN,...,1.8,0.6,2,-0.4,2.3,1.1,N.A,1,N.A,1.7
2010,NaN,NaN,NaN,-,NaN,NaN,2.9,3.2,NaN,NaN,...,NaN,NaN,2.3,0.5,NaN,NaN,6.3,NaN,NaN,1.7
2011,NaN,NaN,NaN,-,2.11,NaN,2.51,2.92,NaN,NaN,...,NaN,1.49,2.03,NaN,2.57,NaN,NaN,NaN,NaN,1.68
2012,NaN,NaN,NaN,-,NaN,NaN,2.54,NaN,NaN,NaN,...,NaN,NaN,4.76,NaN,NaN,NaN,NaN,NaN,NaN,1.68
2013,NaN,NaN,0.508,-,0.116,0.708,1.859,3.383,NaN,NaN,...,NaN,NaN,4.008,NaN,NaN,2.741,4.775,NaN,NaN,1.683
2014,NaN,NaN,0.433,-,NaN,7.391,1.616,2.025,NaN,NaN,...,NaN,NaN,3.15,0.47,NaN,NaN,4.608,5.091,NaN,1.366
2015,NaN,NaN,NaN,-,NaN,1.341,NaN,1.325,1.025,NaN,...,NaN,1.241,2.983,NaN,2.275,NaN,4.55,NaN,NaN,0.2583
2016,NaN,NaN,NaN,-,NaN,0.583,NaN,1.367,1.575,NaN,...,NaN,NaN,NaN,NaN,2.817,NaN,4.616,NaN,NaN,0.3

In [690]:
trans = df.T
trans

,Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Arghakhanchi (Khanchikot),6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bardia (Chishapani),7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Rupandehi,Bhairahawa Agriculture",2.7,2.7,NaN,NaN,NaN,NaN,NaN,NaN,0.508,0.433,NaN,NaN
3,"Bhojpur,Bhojpur*",-,-,-,-,-,-,-,-,-,-,-,-
4,"Dadeldhura,Dadeldhura",3.4,2.9,2.6,2.6,2.8,NaN,2.11,NaN,0.116,NaN,NaN,NaN
5,"Dhankuta,Pakhribas",1.2,1.3,N.A,0.9,N.A,NaN,NaN,NaN,0.708,7.391,1.341,0.583
6,"Dhankuta, Dhankuta",3.9,3.5,3.2,3.3,3.1,2.9,2.51,2.54,1.859,1.616,NaN,NaN
7,Dolakha (Jiri),3.2,3.1,N.A,3,N.A,3.2,2.92,NaN,3.383,2.025,1.325,1.367
8,"Doti, Dipayal",1.4,2,1.9,1.5,1.6,NaN,NaN,NaN,NaN,NaN,1.025,1.575
9,"Ilam , Ilam Tea State",1.2,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Jhapa, Kankai Gaida",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Mustang,Jomsom",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"Jumla,Jumla",5.4,5.6,5.3,4.6,4.8,4.4,4.16,NaN,4.058,4.208,4.55,4.258
13,"Kailai, Dhangadhi",NaN,NaN,1.7,1.7,1.6,NaN,NaN,NaN,NaN,0.25,0.092,NaN
14,"Kanchanpur,Mahendranagar",2.4,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"Kaski ,Lumle",1.3,1.3,1.4,1.2,0.8,0.7,0.76,NaN,NaN,4.833,NaN,NaN
16,"Kathmandu ,Kathmandu Airport",0.8,NaN,0.7,0.9,0.6,0.6,NaN,NaN,0.5,0.591,0.7,NaN
17,"Lalitpur ,Khumaltar",3,3,3,3.2,3,3,2.68,NaN,2.633,NaN,2.558,2.483
18,"Kaski, Malepatan",0.3,0.3,0.4,0.3,0.2,0.28,NaN,NaN,0.991,NaN,1.133,0.558
19,"Morang, Biratnagar Airport",1.8,NaN,5.9,6.5,5,2.8,1.24,2.25,NaN,NaN,NaN,NaN
20,"Bhaktpur, Nagarkot",4.3,3.7,2.9,2.7,0.9,NaN,NaN,NaN,1,0.9,0.766,0.775
21,"Banke, Nepalganj",2.8,2,1.9,1.5,1.6,NaN,NaN,NaN,0.875,0.833,NaN,NaN
22,"Banke,Khajura",2.2,1.9,1.9,1.9,1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"Banke, Sikta",1.9,1.5,0.6,0.8,0.6,NaN,1.49,NaN,NaN,NaN,1.241,NaN
24,"Okhaldhunga,Okhaldhunga",2.7,4.3,4.3,3.8,2,2.3,2.03,4.76,4.008,3.15,2.983,NaN
25,"Parsa, Parwanipur",2.5,1.7,0.7,1.3,-0.4,0.5,NaN,NaN,NaN,0.47,NaN,NaN
26,"Kaski, Pokhara Airport",2.3,NaN,1.9,2.1,2.3,NaN,2.57,NaN,NaN,NaN,2.275,2.817
27,"Siraha, Lahan",3.9,NaN,N.A,1.9,1.1,NaN,NaN,NaN,2.741,NaN,NaN,NaN
28,"Sunsari ,Tarahara",4.5,7,6.4,6.2,N.A,6.3,NaN,NaN,4.775,4.608,4.55,4.616
29,"Surkhet ,Birendranagar",1.6,1.2,1.3,1.6,1,NaN,NaN,NaN,NaN,5.091,NaN,NaN
30,"Surkhet ,Pusmacamp",1.6,1.9,1.6,N.A,N.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"Taplejung, Taplejung",2.5,NaN,1.5,1.8,1.7,1.7,1.68,1.68,1.683,1.366,0.2583,0.3

In [691]:
df = df.drop([3,10,11],axis = 1)

In [692]:
df.columns = range(29)
df[4][3] = 2.6
df[4][5] = 2.8
df[6][3] = 3.2
df[6][5] = 3.1
df[24][3] = 1.9
df[25][5] = 1.1
df[27][4] = 1.6
df[27][5] = 1
df

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
Year,Arghakhanchi (Khanchikot),Bardia (Chishapani),"Rupandehi,Bhairahawa Agriculture","Dadeldhura,Dadeldhura","Dhankuta,Pakhribas","Dhankuta, Dhankuta",Dolakha (Jiri),"Doti, Dipayal","Ilam , Ilam Tea State","Jumla,Jumla",...,"Banke,Khajura","Banke, Sikta","Okhaldhunga,Okhaldhunga","Parsa, Parwanipur","Kaski, Pokhara Airport","Siraha, Lahan","Sunsari ,Tarahara","Surkhet ,Birendranagar","Surkhet ,Pusmacamp","Taplejung, Taplejung"
2005,6.6,7.2,2.7,3.4,1.2,3.9,3.2,1.4,1.2,5.4,...,2.2,1.9,2.7,2.5,2.3,3.9,4.5,1.6,1.6,2.5
2006,NaN,NaN,2.7,2.9,1.3,3.5,3.1,2,1.2,5.6,...,1.9,1.5,4.3,1.7,NaN,NaN,7,1.2,1.9,NaN
2007,NaN,NaN,NaN,2.6,2.6,3.2,3.2,1.9,NaN,5.3,...,1.9,0.6,4.3,0.7,1.9,1.9,6.4,1.3,1.6,1.5
2008,NaN,NaN,NaN,2.6,0.9,3.3,3,1.5,NaN,4.6,...,1.9,0.8,3.8,1.3,2.1,1.9,6.2,1.6,1.6,1.8
2009,NaN,NaN,NaN,2.8,2.8,3.1,3.1,1.6,NaN,4.8,...,1.8,0.6,2,-0.4,2.3,1.1,1.1,1,1,1.7
2010,NaN,NaN,NaN,NaN,NaN,2.9,3.2,NaN,NaN,4.4,...,NaN,NaN,2.3,0.5,NaN,NaN,6.3,NaN,NaN,1.7
2011,NaN,NaN,NaN,2.11,NaN,2.51,2.92,NaN,NaN,4.16,...,NaN,1.49,2.03,NaN,2.57,NaN,NaN,NaN,NaN,1.68
2012,NaN,NaN,NaN,NaN,NaN,2.54,NaN,NaN,NaN,NaN,...,NaN,NaN,4.76,NaN,NaN,NaN,NaN,NaN,NaN,1.68
2013,NaN,NaN,0.508,0.116,0.708,1.859,3.383,NaN,NaN,4.058,...,NaN,NaN,4.008,NaN,NaN,2.741,4.775,NaN,NaN,1.683
2014,NaN,NaN,0.433,NaN,7.391,1.616,2.025,NaN,NaN,4.208,...,NaN,NaN,3.15,0.47,NaN,NaN,4.608,5.091,NaN,1.366
2015,NaN,NaN,NaN,NaN,1.341,NaN,1.325,1.025,NaN,4.55,...,NaN,1.241,2.983,NaN,2.275,NaN,4.55,NaN,NaN,0.2583
2016,NaN,NaN,NaN,NaN,0.583,NaN,1.367,1.575,NaN,4.258,...,NaN,NaN,NaN,NaN,2.817,NaN,4.616,NaN,NaN,0.3

In [693]:
cols = []
for i in range(29):
    cols.append(df[i][0])
print(cols)
len(cols)
# for i in range()
# for i in range(len(df))
# df[1][0]

['Arghakhanchi (Khanchikot)', 'Bardia (Chishapani)', 'Rupandehi,Bhairahawa Agriculture', 'Dadeldhura,Dadeldhura', 'Dhankuta,Pakhribas', 'Dhankuta, Dhankuta', 'Dolakha (Jiri)', 'Doti, Dipayal', 'Ilam , Ilam Tea State', 'Jumla,Jumla', 'Kailai, Dhangadhi', 'Kanchanpur,Mahendranagar', 'Kaski ,Lumle', 'Kathmandu ,Kathmandu Airport', 'Lalitpur ,Khumaltar', 'Kaski, Malepatan', 'Morang, Biratnagar Airport', 'Bhaktpur, Nagarkot', 'Banke, Nepalganj', 'Banke,Khajura', 'Banke, Sikta', 'Okhaldhunga,Okhaldhunga', 'Parsa, Parwanipur', 'Kaski, Pokhara Airport', 'Siraha, Lahan', 'Sunsari ,Tarahara', 'Surkhet ,Birendranagar', 'Surkhet ,Pusmacamp', 'Taplejung, Taplejung']

29

In [694]:
df.columns = cols

In [695]:
df.index

Index(['Year', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016'],
      dtype='object')

In [696]:
df = df.drop(["Year"],axis=0)

In [697]:
# trans = df.T
# trans

In [698]:
df.columns

Index(['Arghakhanchi (Khanchikot)', 'Bardia (Chishapani)',
       'Rupandehi,Bhairahawa Agriculture', 'Dadeldhura,Dadeldhura',
       'Dhankuta,Pakhribas', 'Dhankuta, Dhankuta', 'Dolakha (Jiri)',
       'Doti, Dipayal', 'Ilam , Ilam Tea State', 'Jumla,Jumla',
       'Kailai, Dhangadhi', 'Kanchanpur,Mahendranagar', 'Kaski ,Lumle',
       'Kathmandu ,Kathmandu Airport', 'Lalitpur ,Khumaltar',
       'Kaski, Malepatan', 'Morang, Biratnagar Airport', 'Bhaktpur, Nagarkot',
       'Banke, Nepalganj', 'Banke,Khajura', 'Banke, Sikta',
       'Okhaldhunga,Okhaldhunga', 'Parsa, Parwanipur',
       'Kaski, Pokhara Airport', 'Siraha, Lahan', 'Sunsari ,Tarahara',
       'Surkhet ,Birendranagar', 'Surkhet ,Pusmacamp', 'Taplejung, Taplejung'],
      dtype='object')

In [699]:
df.dtypes

Arghakhanchi (Khanchikot)           object
Bardia (Chishapani)                 object
Rupandehi,Bhairahawa Agriculture    object
Dadeldhura,Dadeldhura               object
Dhankuta,Pakhribas                  object
Dhankuta, Dhankuta                  object
Dolakha (Jiri)                      object
Doti, Dipayal                       object
Ilam , Ilam Tea State               object
Jumla,Jumla                         object
Kailai, Dhangadhi                   object
Kanchanpur,Mahendranagar            object
Kaski ,Lumle                        object
Kathmandu ,Kathmandu Airport        object
Lalitpur ,Khumaltar                 object
Kaski, Malepatan                    object
Morang, Biratnagar Airport          object
Bhaktpur, Nagarkot                  object
Banke, Nepalganj                    object
Banke,Khajura                       object
Banke, Sikta                        object
Okhaldhunga,Okhaldhunga             object
Parsa, Parwanipur                   object
Kaski, Pokhara Airport              object
Siraha, Lahan                       object
Sunsari ,Tarahara                   object
Surkhet ,Birendranagar              object
Surkhet ,Pusmacamp                  object
Taplejung, Taplejung                object
dtype: object

In [700]:
df = df.astype(float)

In [701]:
meean = df['Arghakhanchi (Khanchikot)'].mean()
for place in cols:
    df[place] = df[place].fillna(df[place].mean())
df

,Arghakhanchi (Khanchikot),Bardia (Chishapani),"Rupandehi,Bhairahawa Agriculture","Dadeldhura,Dadeldhura","Dhankuta,Pakhribas","Dhankuta, Dhankuta",Dolakha (Jiri),"Doti, Dipayal","Ilam , Ilam Tea State","Jumla,Jumla",...,"Banke,Khajura","Banke, Sikta","Okhaldhunga,Okhaldhunga","Parsa, Parwanipur","Kaski, Pokhara Airport","Siraha, Lahan","Sunsari ,Tarahara","Surkhet ,Birendranagar","Surkhet ,Pusmacamp","Taplejung, Taplejung"
2005,6.6,7.2,2.70000,3.400000,1.200000,3.9000,3.200000,1.400000,1.2,5.400000,...,2.20,1.900000,2.700000,2.500000,2.300000,3.9000,4.5000,1.600000,1.60,2.500000
2006,6.6,7.2,2.70000,2.900000,1.300000,3.5000,3.100000,2.000000,1.2,5.600000,...,1.90,1.500000,4.300000,1.700000,2.323143,2.3082,7.0000,1.200000,1.90,1.469755
2007,6.6,7.2,1.58525,2.600000,2.600000,3.2000,3.200000,1.900000,1.2,5.300000,...,1.90,0.600000,4.300000,0.700000,1.900000,1.9000,6.4000,1.300000,1.60,1.500000
2008,6.6,7.2,1.58525,2.600000,0.900000,3.3000,3.000000,1.500000,1.2,4.600000,...,1.90,0.800000,3.800000,1.300000,2.100000,1.9000,6.2000,1.600000,1.60,1.800000
2009,6.6,7.2,1.58525,2.800000,2.800000,3.1000,3.100000,1.600000,1.2,4.800000,...,1.80,0.600000,2.000000,-0.400000,2.300000,1.1000,1.1000,1.000000,1.00,1.700000
2010,6.6,7.2,1.58525,2.360857,2.091444,2.9000,3.200000,1.571429,1.2,4.400000,...,1.94,1.161571,2.300000,0.500000,2.323143,2.3082,6.3000,1.965167,1.54,1.700000
2011,6.6,7.2,1.58525,2.110000,2.091444,2.5100,2.920000,1.571429,1.2,4.160000,...,1.94,1.490000,2.030000,0.967143,2.570000,2.3082,5.0049,1.965167,1.54,1.680000
2012,6.6,7.2,1.58525,2.360857,2.091444,2.5400,2.710909,1.571429,1.2,4.666727,...,1.94,1.161571,4.760000,0.967143,2.323143,2.3082,5.0049,1.965167,1.54,1.680000
2013,6.6,7.2,0.50800,0.116000,0.708000,1.8590,3.383000,1.571429,1.2,4.058000,...,1.94,1.161571,4.008000,0.967143,2.323143,2.7410,4.7750,1.965167,1.54,1.683000
2014,6.6,7.2,0.43300,2.360857,7.391000,1.6160,2.025000,1.571429,1.2,4.208000,...,1.94,1.161571,3.150000,0.470000,2.323143,2.3082,4.6080,5.091000,1.54,1.366000
2015,6.6,7.2,1.58525,2.360857,1.341000,2.8425,1.325000,1.025000,1.2,4.550000,...,1.94,1.241000,2.983000,0.967143,2.275000,2.3082,4.5500,1.965167,1.54,0.258300
2016,6.6,7.2,1.58525,2.360857,0.583000,2.8425,1.367000,1.575000,1.2,4.258000,...,1.94,1.161571,3.302818,0.967143,2.817000,2.3082,4.6160,1.965167,1.54,0.300000

In [702]:
df.to_csv('file1.csv')

In [705]:
# df.loc["Speed"] = df.sum()
df = df.append(df.sum().rename('Total'))
df

,Arghakhanchi (Khanchikot),Bardia (Chishapani),"Rupandehi,Bhairahawa Agriculture","Dadeldhura,Dadeldhura","Dhankuta,Pakhribas","Dhankuta, Dhankuta",Dolakha (Jiri),"Doti, Dipayal","Ilam , Ilam Tea State","Jumla,Jumla",...,"Banke,Khajura","Banke, Sikta","Okhaldhunga,Okhaldhunga","Parsa, Parwanipur","Kaski, Pokhara Airport","Siraha, Lahan","Sunsari ,Tarahara","Surkhet ,Birendranagar","Surkhet ,Pusmacamp","Taplejung, Taplejung"
2005,6.6,7.2,2.70000,3.400000,1.200000,3.9000,3.200000,1.400000,1.2,5.400000,...,2.20,1.900000,2.700000,2.500000,2.300000,3.9000,4.5000,1.600000,1.60,2.500000
2006,6.6,7.2,2.70000,2.900000,1.300000,3.5000,3.100000,2.000000,1.2,5.600000,...,1.90,1.500000,4.300000,1.700000,2.323143,2.3082,7.0000,1.200000,1.90,1.469755
2007,6.6,7.2,1.58525,2.600000,2.600000,3.2000,3.200000,1.900000,1.2,5.300000,...,1.90,0.600000,4.300000,0.700000,1.900000,1.9000,6.4000,1.300000,1.60,1.500000
2008,6.6,7.2,1.58525,2.600000,0.900000,3.3000,3.000000,1.500000,1.2,4.600000,...,1.90,0.800000,3.800000,1.300000,2.100000,1.9000,6.2000,1.600000,1.60,1.800000
2009,6.6,7.2,1.58525,2.800000,2.800000,3.1000,3.100000,1.600000,1.2,4.800000,...,1.80,0.600000,2.000000,-0.400000,2.300000,1.1000,1.1000,1.000000,1.00,1.700000
2010,6.6,7.2,1.58525,2.360857,2.091444,2.9000,3.200000,1.571429,1.2,4.400000,...,1.94,1.161571,2.300000,0.500000,2.323143,2.3082,6.3000,1.965167,1.54,1.700000
2011,6.6,7.2,1.58525,2.110000,2.091444,2.5100,2.920000,1.571429,1.2,4.160000,...,1.94,1.490000,2.030000,0.967143,2.570000,2.3082,5.0049,1.965167,1.54,1.680000
2012,6.6,7.2,1.58525,2.360857,2.091444,2.5400,2.710909,1.571429,1.2,4.666727,...,1.94,1.161571,4.760000,0.967143,2.323143,2.3082,5.0049,1.965167,1.54,1.680000
2013,6.6,7.2,0.50800,0.116000,0.708000,1.8590,3.383000,1.571429,1.2,4.058000,...,1.94,1.161571,4.008000,0.967143,2.323143,2.7410,4.7750,1.965167,1.54,1.683000
2014,6.6,7.2,0.43300,2.360857,7.391000,1.6160,2.025000,1.571429,1.2,4.208000,...,1.94,1.161571,3.150000,0.470000,2.323143,2.3082,4.6080,5.091000,1.54,1.366000
2015,6.6,7.2,1.58525,2.360857,1.341000,2.8425,1.325000,1.025000,1.2,4.550000,...,1.94,1.241000,2.983000,0.967143,2.275000,2.3082,4.5500,1.965167,1.54,0.258300
2016,6.6,7.2,1.58525,2.360857,0.583000,2.8425,1.367000,1.575000,1.2,4.258000,...,1.94,1.161571,3.302818,0.967143,2.817000,2.3082,4.6160,1.965167,1.54,0.300000
Total,79.2,86.4,19.02300,28.330286,25.097333,34.1100,32.530909,18.857143,14.4,56.000727,...,23.28,13.938857,39.633818,11.605714,27.877714,27.6984,60.0588,23.582000,18.48,17.637055

In [679]:
df

,Arghakhanchi (Khanchikot),Bardia (Chishapani),"Rupandehi,Bhairahawa Agriculture","Dadeldhura,Dadeldhura","Dhankuta,Pakhribas","Dhankuta, Dhankuta",Dolakha (Jiri),"Doti, Dipayal","Ilam , Ilam Tea State","Jumla,Jumla",...,"Banke,Khajura","Banke, Sikta","Okhaldhunga,Okhaldhunga","Parsa, Parwanipur","Kaski, Pokhara Airport","Siraha, Lahan","Sunsari ,Tarahara","Surkhet ,Birendranagar","Surkhet ,Pusmacamp","Taplejung, Taplejung"
2005,6.6,7.2,2.70000,3.400000,1.200000,3.9000,3.200000,1.400000,1.2,5.400000,...,2.20,1.900000,2.700000,2.500000,2.300000,3.9000,4.5000,1.600000,1.60,2.500000
2006,6.6,7.2,2.70000,2.900000,1.300000,3.5000,3.100000,2.000000,1.2,5.600000,...,1.90,1.500000,4.300000,1.700000,2.323143,2.3082,7.0000,1.200000,1.90,1.469755
2007,6.6,7.2,1.58525,2.600000,2.600000,3.2000,3.200000,1.900000,1.2,5.300000,...,1.90,0.600000,4.300000,0.700000,1.900000,1.9000,6.4000,1.300000,1.60,1.500000
2008,6.6,7.2,1.58525,2.600000,0.900000,3.3000,3.000000,1.500000,1.2,4.600000,...,1.90,0.800000,3.800000,1.300000,2.100000,1.9000,6.2000,1.600000,1.60,1.800000
2009,6.6,7.2,1.58525,2.800000,2.800000,3.1000,3.100000,1.600000,1.2,4.800000,...,1.80,0.600000,2.000000,-0.400000,2.300000,1.1000,1.1000,1.000000,1.00,1.700000
2010,6.6,7.2,1.58525,2.360857,2.091444,2.9000,3.200000,1.571429,1.2,4.400000,...,1.94,1.161571,2.300000,0.500000,2.323143,2.3082,6.3000,1.965167,1.54,1.700000
2011,6.6,7.2,1.58525,2.110000,2.091444,2.5100,2.920000,1.571429,1.2,4.160000,...,1.94,1.490000,2.030000,0.967143,2.570000,2.3082,5.0049,1.965167,1.54,1.680000
2012,6.6,7.2,1.58525,2.360857,2.091444,2.5400,2.710909,1.571429,1.2,4.666727,...,1.94,1.161571,4.760000,0.967143,2.323143,2.3082,5.0049,1.965167,1.54,1.680000
2013,6.6,7.2,0.50800,0.116000,0.708000,1.8590,3.383000,1.571429,1.2,4.058000,...,1.94,1.161571,4.008000,0.967143,2.323143,2.7410,4.7750,1.965167,1.54,1.683000
2014,6.6,7.2,0.43300,2.360857,7.391000,1.6160,2.025000,1.571429,1.2,4.208000,...,1.94,1.161571,3.150000,0.470000,2.323143,2.3082,4.6080,5.091000,1.54,1.366000
2015,6.6,7.2,1.58525,2.360857,1.341000,2.8425,1.325000,1.025000,1.2,4.550000,...,1.94,1.241000,2.983000,0.967143,2.275000,2.3082,4.5500,1.965167,1.54,0.258300
2016,6.6,7.2,1.58525,2.360857,0.583000,2.8425,1.367000,1.575000,1.2,4.258000,...,1.94,1.161571,3.302818,0.967143,2.817000,2.3082,4.6160,1.965167,1.54,0.300000
Speed,79.2,86.4,19.02300,28.330286,25.097333,34.1100,32.530909,18.857143,14.4,56.000727,...,23.28,13.938857,39.633818,11.605714,27.877714,27.6984,60.0588,23.582000,18.48,17.637055

In [680]:
trans = df.T
trans

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,Speed
Arghakhanchi (Khanchikot),6.6000,6.600000,6.60000,6.60000,6.60000,6.600000,6.600000,6.600000,6.600000,6.600000,6.600000,6.600000,79.200000
Bardia (Chishapani),7.2000,7.200000,7.20000,7.20000,7.20000,7.200000,7.200000,7.200000,7.200000,7.200000,7.200000,7.200000,86.400000
"Rupandehi,Bhairahawa Agriculture",2.7000,2.700000,1.58525,1.58525,1.58525,1.585250,1.585250,1.585250,0.508000,0.433000,1.585250,1.585250,19.023000
"Dadeldhura,Dadeldhura",3.4000,2.900000,2.60000,2.60000,2.80000,2.360857,2.110000,2.360857,0.116000,2.360857,2.360857,2.360857,28.330286
"Dhankuta,Pakhribas",1.2000,1.300000,2.60000,0.90000,2.80000,2.091444,2.091444,2.091444,0.708000,7.391000,1.341000,0.583000,25.097333
"Dhankuta, Dhankuta",3.9000,3.500000,3.20000,3.30000,3.10000,2.900000,2.510000,2.540000,1.859000,1.616000,2.842500,2.842500,34.110000
Dolakha (Jiri),3.2000,3.100000,3.20000,3.00000,3.10000,3.200000,2.920000,2.710909,3.383000,2.025000,1.325000,1.367000,32.530909
"Doti, Dipayal",1.4000,2.000000,1.90000,1.50000,1.60000,1.571429,1.571429,1.571429,1.571429,1.571429,1.025000,1.575000,18.857143
"Ilam , Ilam Tea State",1.2000,1.200000,1.20000,1.20000,1.20000,1.200000,1.200000,1.200000,1.200000,1.200000,1.200000,1.200000,14.400000
"Jumla,Jumla",5.4000,5.600000,5.30000,4.60000,4.80000,4.400000,4.160000,4.666727,4.058000,4.208000,4.550000,4.258000,56.000727
"Kailai, Dhangadhi",1.0684,1.068400,1.70000,1.70000,1.60000,1.068400,1.068400,1.068400,1.068400,0.250000,0.092000,1.068400,12.820800
"Kanchanpur,Mahendranagar",2.4000,2.100000,2.25000,2.25000,2.25000,2.250000,2.250000,2.250000,2.250000,2.250000,2.250000,2.250000,27.000000
"Kaski ,Lumle",1.3000,1.300000,1.40000,1.20000,0.80000,0.700000,0.760000,1.536625,1.536625,4.833000,1.536625,1.536625,18.439500
"Kathmandu ,Kathmandu Airport",0.8000,0.673875,0.70000,0.90000,0.60000,0.600000,0.673875,0.673875,0.500000,0.591000,0.700000,0.673875,8.086500
"Lalitpur ,Khumaltar",3.0000,3.000000,3.00000,3.20000,3.00000,3.000000,2.680000,2.855400,2.633000,2.855400,2.558000,2.483000,34.264800
"Kaski, Malepatan",0.3000,0.300000,0.40000,0.30000,0.20000,0.280000,0.495778,0.495778,0.991000,0.495778,1.133000,0.558000,5.949333
"Morang, Biratnagar Airport",1.8000,3.641429,5.90000,6.50000,5.00000,2.800000,1.240000,2.250000,3.641429,3.641429,3.641429,3.641429,43.697143
"Bhaktpur, Nagarkot",4.3000,3.700000,2.90000,2.70000,0.90000,1.993444,1.993444,1.993444,1.000000,0.900000,0.766000,0.775000,23.921333
"Banke, Nepalganj",2.8000,2.000000,1.90000,1.50000,1.60000,1.644000,1.644000,1.644000,0.875000,0.833000,1.644000,1.644000,19.728000
"Banke,Khajura",2.2000,1.900000,1.90000,1.90000,1.80000,1.940000,1.940000,1.940000,1.940000,1.940000,1.940000,1.940000,23.280000
"Banke, Sikta",1.9000,1.500000,0.60000,0.80000,0.60000,1.161571,1.490000,1.161571,1.161571,1.161571,1.241000,1.161571,13.938857
"Okhaldhunga,Okhaldhunga",2.7000,4.300000,4.30000,3.80000,2.00000,2.300000,2.030000,4.760000,4.008000,3.150000,2.983000,3.302818,39.633818
"Parsa, Parwanipur",2.5000,1.700000,0.70000,1.30000,-0.40000,0.500000,0.967143,0.967143,0.967143,0.470000,0.967143,0.967143,11.605714
"Kaski, Pokhara Airport",2.3000,2.323143,1.90000,2.10000,2.30000,2.323143,2.570000,2.323143,2.323143,2.323143,2.275000,2.817000,27.877714
"Siraha, Lahan",3.9000,2.308200,1.90000,1.90000,1.10000,2.308200,2.308200,2.308200,2.741000,2.308200,2.308200,2.308200,27.698400
"Sunsari ,Tarahara",4.5000,7.000000,6.40000,6.20000,1.10000,6.300000,5.004900,5.004900,4.775000,4.608000,4.550000,4.616000,60.058800
"Surkhet ,Birendranagar",1.6000,1.200000,1.30000,1.60000,1.00000,1.965167,1.965167,1.965167,1.965167,5.091000,1.965167,1.965167,23.582000
"Surkhet ,Pusmacamp",1.6000,1.900000,1.60000,1.60000,1.00000,1.540000,1.540000,1.540000,1.540000,1.540000,1.540000,1.540000,18.480000
"Taplejung, Taplejung",2.5000,1.469755,1.50000,1.80000,1.70000,1.700000,1.680000,1.680000,1.683000,1.366000,0.258300,0.300000,17.637055

In [681]:
df.columns
# df.query('Speed > 50')

Index(['Arghakhanchi (Khanchikot)', 'Bardia (Chishapani)',
       'Rupandehi,Bhairahawa Agriculture', 'Dadeldhura,Dadeldhura',
       'Dhankuta,Pakhribas', 'Dhankuta, Dhankuta', 'Dolakha (Jiri)',
       'Doti, Dipayal', 'Ilam , Ilam Tea State', 'Jumla,Jumla',
       'Kailai, Dhangadhi', 'Kanchanpur,Mahendranagar', 'Kaski ,Lumle',
       'Kathmandu ,Kathmandu Airport', 'Lalitpur ,Khumaltar',
       'Kaski, Malepatan', 'Morang, Biratnagar Airport', 'Bhaktpur, Nagarkot',
       'Banke, Nepalganj', 'Banke,Khajura', 'Banke, Sikta',
       'Okhaldhunga,Okhaldhunga', 'Parsa, Parwanipur',
       'Kaski, Pokhara Airport', 'Siraha, Lahan', 'Sunsari ,Tarahara',
       'Surkhet ,Birendranagar', 'Surkhet ,Pusmacamp', 'Taplejung, Taplejung'],
      dtype='object')